### ISSUE TITLE
Fullscreen button missing in Safari

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#280] opened 2016-07-19 21:21 UTC

**Comment by billtomczak** [comment] 2016-10-12 21:13
I think this has been fixed by b07458e14a53724b2697219d3f6557d61d872f4f. I can't reproduce it anymore at any rate :)

Reopen if this isn't the case

**Closed by billtomczak** 2016-10-12 21:13 UTC

**Comment by htmgarcia** [comment] 2016-10-12 23:02
Thanks @billtomczak!
