### ISSUE TITLE
New quiz still not showing questions

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#232] opened 2016-03-29 14:31 UTC
https://www.ostraining.com/class/moving/quiz/
![screen shot 2016-03-29 at 10 30 43 am](https://cloud.githubusercontent.com/assets/3868028/14111618/5e16c0c2-f599-11e5-91eb-8d12a2250b89.png)

**Comment by billtomczak** [comment] 2016-03-29 19:19
hmmm... now I can't reproduce this. I'll keep this open - let me know when it shows up again.

**Comment by billtomczak** [comment] 2016-03-30 15:12
I'm closing this as probably confusion caused by OSCampus' internal caching of quiz questions. Likely something like #234 will help for debugging by administrators.

**Closed by billtomczak** 2016-03-30 15:12 UTC
Labels: Bug
