### ISSUE TITLE
Merge description fields into one

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#163] opened 2016-02-15 23:12 UTC
In the places where we are using "Introduction" and "Full description" it is possible to merge into one textarea, similar to articles.

> Intro text goes here
> [separator]
> Rest of the text

**Comment by htmgarcia** [comment] 2016-02-25 15:49
Thank you @billtomczak !

**Comment by nicksavov** [comment] 2016-03-11 04:49
@stevejburge , just keep in mind whenever you're creating/editing classes that whatever is above the readmore won't appear in the full description. It will only appear in the intro text.

**Comment by stevejburge** [comment] 2016-03-11 14:27
@nicksavov @billtomczak Could we fix that? That's unexpected behavior compared to normal Joomla content

**Comment by billtomczak** [comment] 2016-03-11 17:43
@nick are you sure? Take a look at https://www.ostraining.com/class/beginner/ for example. The text in the description pane is all the text for that class

**Comment by nicksavov** [comment] 2016-03-11 17:47
Something wonky is going on. My changes to WordPress' Theme Design were lost from last night.

Let me check...

**Comment by nicksavov** [comment] 2016-03-11 17:48
Hmm, looks like I made the change in GhostExplained?!

**Comment by nicksavov** [comment] 2016-03-11 17:50
No, I did it in the live site, because I'm seeing part of the text change after the readmore and it's there.

**Comment by nicksavov** [comment] 2016-03-11 17:55
Everything's working as expected now.

I'm not sure what the issue was, but I can't replicate it anymore. I guess we'll find out later if there some kind of bug or not. Let's close this one for now

**Closed by nicksavov** 2016-03-11 17:55 UTC
Labels: Admin Management, Enhancement

**Comment by billtomczak** [comment] 2016-03-11 18:03
I wonder if it might have been a caching issue?
